### ISSUE TITLE
This project should be in english

### ISSUE THREAD

**Issue by vieiralucas** [chaordic/snippets-ui#3]
Shoudnt?

![alt](http://www.quickmeme.com/img/e2/e2d278c546432c8b0a30ce8982752deb56d0249aff996c923378fdf2524a5981.jpg)

:smile:

**Comment by mwconceicao** [comment]
+1

**Comment by diogomoretti** [comment]
+1, but... open a pull request. the repo is open =]

**Comment by vieiralucas** [comment]
Yeah! Open a PR!!

ohwait...

:smile: will do it
